# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3783d72f6de00b005ebc1a4a4355d49a8e20d253d451f8c83586f22365c279289a3fb867c3497e0018f2f3002f6c9b630e911662cefa8bad6942439c05832914

test:
  secret_key_base: cd831d99114581462c7685a7978f0cf06d984b592cfa49a643fbe205e7d4805f7f34c0f69e8391f6eeeac7c410795c4942d84de3bdbfae88f42e24c7d4767984

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
